apiVersion: v1
kind: Pod
metadata:
 name: {{ .Values.image.name }}
 labels:
  app: {{ .Chart.Name }}
spec:
 containers:
 - image: {{ .Values.image.image }}:{{ .Chart.AppVersion }}
   name: {{ .Values.image.name }}
